name: Build & Deploy Storybook
on:
    push:
        paths: [".storybook/**", "stories/**", "src/**"]
jobs:
    build-and-deploy:
        name: Build & deploy storybook to gh pages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false
            - name: Install and Build
              run: |
                  yarn
                  yarn build-storybook
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.0.0
              with:
                  BRANCH: gh-pages
                  FOLDER: storybook-static
